ALTER TABLE users
ADD COLUMN first_name VARCHAR(255);

ALTER TABLE users
ADD COLUMN surname VARCHAR(255);

ALTER TABLE users
ADD COLUMN function VARCHAR(255);

ALTER TABLE users
ADD COLUMN language VARCHAR(5) NOT NULL DEFAULT 'de';
